export const ADD_ARTICLE = "ADD_ARTICLE";
export const SET_ARTISTS = "SET_ARTISTS";
export const SET_CURRENT_ARTIST = "SET_CURRENT_ARTIST";
export const SET_SHOW_GUESS_RESULT = "SET_SHOW_GUESS_RESULT";
export const SET_ARTIST_COUNTER = "SET_ARTIST_COUNTER";